version: "3.3"

services:
  backend:
    build: backend
    restart: always
#    ports:
#      - "8085:8085"
    expose:
      - "8085"
    environment:
      TZ: "America/New_York"
  frontend:
    build: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8085:8085"
    volumes:
      - ./data/frontend/logs:/var/log/nginx