version: "3.3"

services:
  backend:
    build: backend
    restart: unless-stopped
    #    ports:
    #      - "8085:8085"  # Uncomment this for local debugging, but don't bind to host in production
    expose:
      - "8085"
    environment:
      TZ: "America/New_York"
      CORS_ALLOWED_ORIGINS: "*"  # Change this in production!
  frontend:
    build: frontend
    restart: unless-stopped
    depends_on:
      frontend-build:
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "8085:8085"  # For API proxying to backend through Nginx
    volumes:
      - ./data/frontend/logs:/var/log/nginx
  frontend-build:
    build:
      context: frontend
      dockerfile: Dockerfile-build
    volumes:
      - ./frontend/Environment-Display/dist:/app/Environment-Display/dist
  db:
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "environment_display"
      MYSQL_USER: "environment_display"
      MYSQL_PASSWORD: "changeme"
    expose:
      - "3306"
    ports:
      - "3306:3306"  # Uncomment this for local debugging, but don't bind to host in production
    volumes:
      - ./data/db:/var/lib/mysql